In [1]:
import numpy as np

In [ ]:
lista = [1,2,3,4,5,6,7,8,9]
lista

In [ ]:
arr = np.array(lista)
arr

Creacion matrices

In [9]:
matriz = [[1,2,3],[4,5,6],[7,8,9]]
matriz = np.array(matriz)
matriz

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

Indexing 

In [23]:
arr0 = arr[0:4]
arr1 = arr[:5]
arr2 = arr[3:]


mat1 = matriz[1:,0:2]
mat1


array([[4, 5],
       [7, 8]])

handling steps

In [32]:
arr3 = arr[::3]

mat2 = matriz[::3,:3]
mat2

array([[1, 2, 3]])

el -1? el -3?

In [19]:
arr4 = arr[-3]
arr4

7

In [33]:
matriz[:,-1]

array([3, 6, 9])