In [3]:
import numpy as np

In [4]:
scalar = np.array(42)
scalar.ndim

0

In [5]:
vector = np.array([1,2,3])
vector.ndim

1

In [12]:
mat = np.array([[1,2,3],[4,5,6],[7,8,9]])
mat.ndim

2

In [15]:
tensor = np.array([[[[1,2,3],[4,5,6],[7,8,9]],[[1,2,3],[4,5,6],[7,8,9]],[[1,2,3],[4,5,6],[7,8,9]]],[[[1,2,3],[4,5,6],[7,8,9]],[[1,2,3],[4,5,6],[7,8,9]],[[1,2,3],[4,5,6],[7,8,9]]],[[[1,2,3],[4,5,6],[7,8,9]],[[1,2,3],[4,5,6],[7,8,9]],[[1,2,3],[4,5,6],[7,8,9]]]])
print(tensor)
tensor.ndim

[[[[1 2 3]
   [4 5 6]
   [7 8 9]]

  [[1 2 3]
   [4 5 6]
   [7 8 9]]

  [[1 2 3]
   [4 5 6]
   [7 8 9]]]


 [[[1 2 3]
   [4 5 6]
   [7 8 9]]

  [[1 2 3]
   [4 5 6]
   [7 8 9]]

  [[1 2 3]
   [4 5 6]
   [7 8 9]]]


 [[[1 2 3]
   [4 5 6]
   [7 8 9]]

  [[1 2 3]
   [4 5 6]
   [7 8 9]]

  [[1 2 3]
   [4 5 6]
   [7 8 9]]]]


4

AGREGAR O ELIMINAR DIMENSIONES

In [16]:
vector = np.array([1,2,3], ndmin=10)
print(vector)
vector.ndim

[[[[[[[[[[1 2 3]]]]]]]]]]


10

In [18]:
expand = np.expand_dims(np.array([1,2,3]),axis=0)
print(expand)
expand.ndim

[[1 2 3]]


2

In [20]:
vector = np.array([1,2,3], ndmin=10)
print(vector , vector.ndim)
vector2 = np.squeeze(vector)
print(vector2 ,  vector2.ndim)


[[[[[[[[[[1 2 3]]]]]]]]]] 10
[1 2 3] 1
