In [2]:
import numpy as np

In [3]:
list(range(0,10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

arange

In [4]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Step

In [6]:
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

Matriz de 0 y de 1

In [7]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [8]:
np.ones((10,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

Función linspace sirve para generar numeros random entre desde valor min, valor max, y cuantos datos a generar en una distribucion normalizada

In [9]:
np.linspace(0,10,100)

array([ 0.        ,  0.1010101 ,  0.2020202 ,  0.3030303 ,  0.4040404 ,
        0.50505051,  0.60606061,  0.70707071,  0.80808081,  0.90909091,
        1.01010101,  1.11111111,  1.21212121,  1.31313131,  1.41414141,
        1.51515152,  1.61616162,  1.71717172,  1.81818182,  1.91919192,
        2.02020202,  2.12121212,  2.22222222,  2.32323232,  2.42424242,
        2.52525253,  2.62626263,  2.72727273,  2.82828283,  2.92929293,
        3.03030303,  3.13131313,  3.23232323,  3.33333333,  3.43434343,
        3.53535354,  3.63636364,  3.73737374,  3.83838384,  3.93939394,
        4.04040404,  4.14141414,  4.24242424,  4.34343434,  4.44444444,
        4.54545455,  4.64646465,  4.74747475,  4.84848485,  4.94949495,
        5.05050505,  5.15151515,  5.25252525,  5.35353535,  5.45454545,
        5.55555556,  5.65656566,  5.75757576,  5.85858586,  5.95959596,
        6.06060606,  6.16161616,  6.26262626,  6.36363636,  6.46464646,
        6.56565657,  6.66666667,  6.76767677,  6.86868687,  6.96

la matiz de identidad 1 en la diagonal

In [10]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

Generar aleatorios

In [11]:
np.random.rand(4)

array([0.72721491, 0.2293381 , 0.81949862, 0.24008069])

In [12]:
np.random.rand(4,4)

array([[0.44091514, 0.89913887, 0.45172517, 0.90510489],
       [0.78141   , 0.63184387, 0.51061635, 0.91858837],
       [0.3354031 , 0.46321869, 0.88353945, 0.92221499],
       [0.91143332, 0.05319902, 0.25703016, 0.04829721]])

In [14]:
np.random.rand(4,4,4,4)

array([[[[2.42331878e-01, 6.68739177e-01, 1.26827177e-01,
          7.61733528e-01],
         [1.73681864e-01, 3.98037941e-01, 4.13135923e-01,
          6.98971561e-02],
         [6.36040579e-01, 5.70707399e-01, 8.64856989e-01,
          8.24447692e-01],
         [5.21433422e-02, 6.08250775e-01, 2.58606167e-01,
          8.15384662e-01]],

        [[1.65014747e-02, 2.97215207e-01, 5.80372922e-02,
          6.30142669e-01],
         [2.72812344e-01, 9.42398617e-01, 8.68866962e-01,
          7.10843112e-01],
         [7.11060553e-01, 7.97414684e-02, 6.32292722e-01,
          5.02041420e-01],
         [4.38285805e-01, 9.61124753e-01, 3.64709274e-01,
          8.90693455e-01]],

        [[1.16335538e-01, 1.28490344e-01, 4.44084239e-01,
          1.77704611e-01],
         [1.57960657e-01, 2.95457506e-01, 8.86369579e-01,
          5.25062562e-01],
         [7.97211793e-01, 7.04844406e-01, 4.17873644e-01,
          1.19018802e-01],
         [6.62900445e-04, 1.43921155e-02, 1.28951022e-01,
   

In [19]:
np.random.randint(1,15)

10

In [20]:
np.random.randint(1,100,(10,10))

array([[92, 74, 21,  5, 88, 41, 46, 91,  2, 42],
       [10, 56, 52, 76, 66, 79, 60, 99, 13, 88],
       [76, 91, 66, 99, 71, 64, 29, 21,  6, 88],
       [47, 21, 28, 43, 28, 75, 79, 93, 61, 46],
       [87, 39, 13, 41, 10, 11, 89, 81, 45, 68],
       [43, 28, 72, 31, 74, 24, 15, 15, 96,  9],
       [94, 49, 67, 36, 98, 25, 88, 84, 10, 56],
       [27, 59, 63, 11, 46, 79, 70, 62, 32, 76],
       [11, 24, 44, 30, 88, 68, 83, 32, 86, 31],
       [99, 40, 23, 78, 82, 85, 32, 21, 80, 78]])