In [1]:
import numpy as np

In [3]:
arr = np.random.randint(1,10,(3,2))

Mostrar la forma del array

In [4]:
arr.shape

(3, 2)

Cambiar la forma del array

In [5]:
arr

array([[8, 7],
       [1, 5],
       [9, 7]])

In [6]:
arr.reshape(1,6)

array([[8, 7, 1, 5, 9, 7]])

In [7]:
arr.reshape(2,3)

array([[8, 7, 1],
       [5, 9, 7]])

In [8]:
np.reshape(arr,(1,6))

array([[8, 7, 1, 5, 9, 7]])

In [17]:
arr

array([[8, 7],
       [1, 5],
       [9, 7]])

Reshape tipo C

In [18]:
np.reshape(arr,(2,3),'C')

array([[8, 7, 1],
       [5, 9, 7]])

Reshape tipo F (Fortran)

In [15]:
print(arr)
np.reshape(arr,(2,3),'F')

[[8 7]
 [1 5]
 [9 7]]


array([[8, 9, 5],
       [1, 7, 7]])

De tipo Aleatorio segun el almacenamiento de mi sistema

In [16]:
print(arr)
np.reshape(arr,(2,3),'A')

[[8 7]
 [1 5]
 [9 7]]


array([[8, 7, 1],
       [5, 9, 7]])

NO SE PUEDE CAMBIAR LA FORMA A ALGO QUE NO SOPORTE LA FORMA ORIGINAL DEL ARRAY


SE DEBE MANTENER LA MISMA CANTIDAD DE VALORES