In [6]:
import numpy as np

In [14]:
arr = np.random.randint(1, 20, 10)
matriz = arr.reshape(2,5)
print(arr)
matriz

[ 9  7 13  7  2 10  7  3  8  7]


array([[ 9,  7, 13,  7,  2],
       [10,  7,  3,  8,  7]])

Arrojar el valor máximo

In [15]:
print(arr.max()) 
print(matriz.max()) 

13
13


Podemos regresar los máximos de cada fila o columna especificando el eje. 0 para columnas 1 para filas

In [22]:
print(matriz.max(0)) 
print(matriz.max(1)) 


[10  7 13  8  7]
[13 10]


Tambien tenemos .argmax() que nos devuelve la posición del elemento

In [25]:
print(arr.argmax()) 
print(matriz.argmax(0))
print(matriz.argmax(1))  

2
[1 0 0 1 1]
[2 0]


De forma análoga tenemos .min()

In [31]:
print(arr.min()) 
print(arr.argmin()) 
print(matriz.min())
print(matriz.argmin(0))
print(matriz.argmin(1))  

2
4
2
[0 0 1 0 0]
[4 2]


Podemos saber la diferencia de valor más bajo con el más alto.

In [30]:
print(arr.ptp())
print(matriz.ptp())
print(matriz.ptp(0))
print(matriz.ptp(1))

11
11
[ 1  0 10  1  5]
[11  7]


Para hacer análisis estádistico se tienen la siguientes funciones.

Ordenar los elementos:

In [35]:
arr.sort()
matriz.sort()


Obtener un percentil:

In [36]:
np.percentile(arr, 0)

2.0

Mediana:

In [37]:
np.median(arr)

7.0

Desviación estándar:

In [38]:
np.std(arr)

3.0016662039607267

Varianza:

In [39]:
np.var(arr)

9.01

Promedio:

In [40]:
np.mean(arr)

7.3

Se pueden unir dos arrays por medio de la concatenación

In [41]:
a = np.array([[1,2], [3,4]])
b= np.array([5, 6])
np.concatenate((a,b), axis = 0)

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

El error anterior es debido a a tiene 2 dimensiones mientras que b tiene 1.

In [42]:
print(a.ndim)
b.ndim
b = np.expand_dims(b, axis = 0)
np.concatenate((a,b), axis = 0)

2


array([[1, 2],
       [3, 4],
       [5, 6]])

De igual forma podemos agregarlo en el otro eje

In [43]:
np.concatenate((a,b), axis = 1)

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 2 and the array at index 1 has size 1

Como b es una fila y no una columna, no se puede concatenar a menos que se aplique la transpuesta.

In [44]:
np.concatenate((a,b.T), axis = 1)

array([[1, 2, 5],
       [3, 4, 6]])